import { FormEvent, useState } from "react";
import { ArrowUpRight, Building2, Plus, Sparkles, WalletCards, X } from "lucide-react";
import { Cuenta, financeApi } from "../api";

export default function AccountsPage({ accounts, onChanged }: { accounts: Cuenta[]; onChanged: () => Promise<void> }) {
  const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const data=new FormData(e.currentTarget);try{await financeApi.crearCuenta({nombre:String(data.get("nombre")),tipo:String(data.get("tipo")),saldo:Number(data.get("saldo")),moneda:String(data.get("moneda"))});setOpen(false);await onChanged()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar la cuenta") }finally{setSaving(false)}};
  return <section className="module-page">
    <div className="module-hero"><div><span className="eyebrow text-cyan-200">PATRIMONIO · CUENTAS</span><h2>Tu ecosistema financiero</h2><p>Administra bancos, billeteras digitales y saldos en distintas monedas.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus size={17}/> Nueva cuenta</button><div className="module-orb"/></div>
    <div className="module-stats"><div><span>Cuentas activas</span><strong>{accounts.length}</strong></div><div><span>Monedas</span><strong>{new Set(accounts.map(a=>a.moneda)).size}</strong></div><div><span>Estado</span><strong className="text-emerald-300">Sincronizado</strong></div></div>
    <div className="account-gallery">{accounts.map((account,index)=><article className="bank-card" key={account.id}><div className="bank-shine"/><div className="flex items-start justify-between"><span className={`account-logo logo-${index%4}`}><Building2 size={20}/></span><span className="currency-chip">{account.moneda}</span></div><div><p>{account.tipo}</p><h3>{account.nombre}</h3></div><div className="flex items-end justify-between"><div><span>Saldo disponible</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:account.moneda}).format(account.saldo)}</strong></div><button aria-label={`Abrir ${account.nombre}`}><ArrowUpRight size={18}/></button></div></article>)}</div>
    <div className="module-insight"><Sparkles/><div><strong>Vista consolidada</strong><p>El Dashboard convierte automáticamente estos saldos a COP sin alterar la moneda original de cada cuenta.</p></div></div>
    {open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVA CUENTA</span><h3>Conecta tu dinero</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{error&&<p className="form-error">{error}</p>}<label>Nombre<input name="nombre" required placeholder="Ej: Bancolombia"/></label><div className="form-grid"><label>Tipo<select name="tipo"><option>Ahorros</option><option>Corriente</option><option>Efectivo</option><option>Inversión</option></select></label><label>Moneda<select name="moneda"><option>COP</option><option>USD</option><option>EUR</option></select></label></div><label>Saldo inicial<input name="saldo" type="number" min="0" step="0.01" defaultValue="0" required/></label><button className="modal-submit" disabled={saving}><WalletCards size={17}/>{saving?"Guardando…":"Crear cuenta"}</button></form></div>}
  </section>;
}
