import { FormEvent, useState } from "react";
import { Building2, Edit3, Plus, Sparkles, Trash2, WalletCards, X } from "lucide-react";
import { Cuenta, financeApi } from "../api";
import ConfirmDialog from "../components/ConfirmDialog";

export default function AccountsPage({accounts,onChanged}:{accounts:Cuenta[];onChanged:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Cuenta|null>(null),[deleting,setDeleting]=useState<Cuenta|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);try{if(editing)await financeApi.actualizarCuenta(editing.id,{nombre:String(d.get("nombre")),tipo:String(d.get("tipo")),moneda:String(d.get("moneda")),color:editing.color||"#6255e7",icono:editing.icono||"🏦",institucion:String(d.get("institucion")),activa:d.get("activa")==="on"});else await financeApi.crearCuenta({nombre:String(d.get("nombre")),tipo:String(d.get("tipo")),saldo:Number(d.get("saldo")),moneda:String(d.get("moneda")),institucion:String(d.get("institucion"))});setOpen(false);setEditing(null);await onChanged()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
 const erase=async()=>{if(!deleting)return;setSaving(true);setError("");try{await financeApi.eliminarCuenta(deleting.id);setDeleting(null);await onChanged()}catch(err){setError(err instanceof Error?err.message:"No fue posible eliminar") }finally{setSaving(false)}};
 return <section className="module-page"><div className="module-hero"><div><span className="eyebrow text-cyan-200">DÓNDE ESTÁ TU DINERO</span><h2>Cuentas y saldos</h2><p>Registra cada banco, billetera o efectivo. Sus saldos forman tu patrimonio y se actualizan con los movimientos.</p></div><button className="primary-action" onClick={()=>{setEditing(null);setOpen(true)}}><Plus/> Nueva cuenta</button><div className="module-orb"/></div>
 <div className="module-stats"><div><span>Cuentas activas</span><strong>{accounts.filter(a=>a.activa).length}</strong></div><div><span>Monedas</span><strong>{new Set(accounts.filter(a=>a.activa).map(a=>a.moneda)).size}</strong></div><div><span>Histórico</span><strong>{accounts.filter(a=>!a.activa).length} desactivadas</strong></div></div>{error&&<p className="form-error">{error}</p>}
 <div className="account-gallery">{accounts.map((account,index)=><article className={`bank-card ${account.activa?"":"opacity-60"}`} key={account.id}><div className="bank-shine"/><div className="flex items-start justify-between"><span className={`account-logo logo-${index%4}`}><Building2/></span><span className="currency-chip">{account.activa?account.moneda:"Histórica"}</span></div><div><p>{account.institucion||account.tipo}</p><h3>{account.nombre}</h3><small>{account.tipo}</small></div><div className="flex items-end justify-between"><div><span>{account.activa?"Saldo disponible":"Saldo al desactivar"}</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:account.moneda}).format(account.saldo)}</strong></div><div className="bank-actions"><button title="Editar o cambiar estado" onClick={()=>{setEditing(account);setOpen(true)}}><Edit3/></button><button title="Eliminar" onClick={()=>setDeleting(account)}><Trash2/></button></div></div></article>)}</div>
 <div className="module-insight"><Sparkles/><div><strong>Vista consolidada</strong><p>El Dashboard convierte automáticamente estos saldos a COP sin alterar la moneda original.</p></div></div>
 {deleting&&<ConfirmDialog title={`Eliminar ${deleting.nombre}`} description={`Saldo actual: ${new Intl.NumberFormat("es-CO",{style:"currency",currency:deleting.moneda}).format(deleting.saldo)}. Si tiene movimientos, FinanceOS impedirá eliminarla para proteger tu historial.`} busy={saving} onCancel={()=>setDeleting(null)} onConfirm={()=>void erase()}/>} 
 {open&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">{editing?"EDITAR":"NUEVA"} CUENTA</span><h3>{editing?"Actualiza la cuenta":"Conecta tu dinero"}</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div><label>Nombre<input name="nombre" required defaultValue={editing?.nombre}/></label><label>Entidad o institución<input name="institucion" maxLength={100} placeholder="Banco, billetera o entidad" defaultValue={editing?.institucion}/></label><div className="form-grid"><label>Tipo<select name="tipo" defaultValue={editing?.tipo||"Ahorros"}><option>Ahorros</option><option>Corriente</option><option>Efectivo</option><option>Inversión</option></select></label><label>Moneda<select name="moneda" defaultValue={editing?.moneda||"COP"}><option>COP</option><option>USD</option><option>EUR</option></select></label></div>{!editing&&<label>Saldo inicial<input name="saldo" type="number" min="0" step="0.01" defaultValue="0"/></label>}{editing&&<label className="flex items-center gap-3"><input name="activa" type="checkbox" defaultChecked={editing.activa}/><span>Cuenta activa y disponible para movimientos</span></label>}<button className="modal-submit" disabled={saving}><WalletCards/>{saving?"Guardando…":"Guardar cuenta"}</button></form></div>}
 </section>;
}
