import { FormEvent, useEffect, useState } from "react";
import { Camera, CircleDollarSign, KeyRound, LockKeyhole, MailCheck, ShieldCheck, UserPlus, WalletCards } from "lucide-react";
import { financeApi } from "../api";

type Props={configuracionInicial:boolean;registroPublico:boolean;aprovisionamientoLocalRequerido?:boolean;onAuthenticated:()=>void};

export default function AuthPage({configuracionInicial,registroPublico,aprovisionamientoLocalRequerido=false,onAuthenticated}:Props){
  const[registro,setRegistro]=useState(configuracionInicial);
  const[recuperar,setRecuperar]=useState(false),[mfa,setMfa]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const params=new URLSearchParams(window.location.search),token=params.get("token"),ruta=window.location.pathname;
  useEffect(()=>{if(!token||ruta!=="/verificar-correo")return;setBusy(true);financeApi.verificarCorreo(token).then(r=>{setMessage(r.mensaje);history.replaceState({},"","/")}).catch(e=>setError(e instanceof Error?e.message:"No se pudo verificar")).finally(()=>setBusy(false))},[]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");setMessage("");const data=new FormData(event.currentTarget);try{if(ruta==="/recuperar-clave"&&token){const r=await financeApi.restablecerPassword(token,String(data.get("password")));setMessage(r.mensaje);history.replaceState({},"","/");setRecuperar(false);setRegistro(false)}else if(recuperar){const r=await financeApi.solicitarRecuperacion(String(data.get("correo")));setMessage(r.mensaje)}else if(registro){await financeApi.registrarPropietario({nombre:String(data.get("nombre")),correo:String(data.get("correo")),password:String(data.get("password"))});if(registroPublico){setMessage("Cuenta creada. Revisa tu correo para verificarla antes de entrar.");setRegistro(false)}else onAuthenticated()}else{await financeApi.iniciarSesion({correo:String(data.get("correo")),password:String(data.get("password")),mfa_codigo:String(data.get("mfa_codigo")||"")||undefined});onAuthenticated()}}catch(err){const texto=err instanceof Error?err.message:"No fue posible continuar";if(texto==="MFA_REQUIRED"){setMfa(true);setError("Ingresa el código de seis dígitos de tu aplicación autenticadora.")}else setError(texto)}finally{setBusy(false)}};
  const inicialLocal=configuracionInicial&&!registroPublico;
  const cambiando=ruta==="/recuperar-clave"&&Boolean(token);
  const titulo=cambiando?"Crea una nueva clave":recuperar?"Recupera tu acceso":registro?(inicialLocal?"Configura FinanceOS":"Crea tu espacio"):"Bienvenido de nuevo";
  return <main className="auth-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="auth-layout">
    <section className="auth-explainer"><span className="eyebrow">TU CENTRO FINANCIERO PRIVADO</span><h2>Entiende FinanceOS antes de comenzar</h2><p>Web y celular comparten la misma información. Cada operación se valida en el servidor y tus datos nunca se mezclan con los de otra persona.</p><div className="auth-benefits">
      <article><span><WalletCards/></span><div><strong>Una cuenta por persona</strong><p>El primer usuario administra la instalación y crea accesos independientes para los demás.</p></div></article>
      <article><span><Camera/></span><div><strong>Facturas inteligentes</strong><p>Fotografía un recibo desde el celular o sube un PDF; siempre revisarás los datos antes de guardar.</p></div></article>
      <article><span><ShieldCheck/></span><div><strong>Seguridad adicional</strong><p>Después de entrar podrás activar MFA desde la guía inicial o Configuración.</p></div></article>
    </div>{!configuracionInicial&&!registroPublico&&<div className="access-explanation"><UserPlus/><div><strong>¿Todavía no tienes usuario?</strong><p>Por seguridad, el administrador debe crearlo desde Configuración → Personas con acceso.</p></div></div>}</section>
    <section className="auth-card"><span className="auth-brand">{recuperar||cambiando?<KeyRound/>:message?<MailCheck/>:<CircleDollarSign/>}</span><span className="eyebrow">FINANCEOS · ACCESO SEGURO</span><h1>{titulo}</h1><p>{cambiando?"El enlace es de un solo uso; al cambiar la clave cerraremos las sesiones anteriores.":recuperar?"Te enviaremos un enlace temporal si encontramos la cuenta.":registro?(inicialLocal?"Este primer usuario será el superadministrador y podrá crear accesos para otras personas.":"Regístrate como usuario. Tus datos financieros estarán separados de los demás."):"Inicia sesión para acceder únicamente a tus datos financieros."}</p>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}{registro&&aprovisionamientoLocalRequerido?<div className="error-banner"><strong>Configuración protegida</strong><br/>En producción el primer administrador se crea directamente en el servidor con <code>python scripts/create_superadmin.py --nombre "Administrador" --correo "tu@correo.com"</code>. Ningún secreto de instalación pasa por el navegador.</div>:<form onSubmit={submit}>{registro&&!recuperar&&!cambiando&&<label>Nombre<input name="nombre" minLength={2} maxLength={100} autoComplete="name" required/></label>}{!cambiando&&<label>Correo<input name="correo" type="email" autoComplete="email" required/></label>}{!recuperar&&<label>{cambiando?"Nueva contraseña":"Contraseña"}<input name="password" type="password" minLength={registro||cambiando?12:1} maxLength={128} autoComplete={registro||cambiando?"new-password":"current-password"} required/></label>}{mfa&&!registro&&!recuperar&&!cambiando&&<label>Código de seguridad<input name="mfa_codigo" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required/></label>}{(registro||cambiando)&&<small>Mínimo 12 caracteres, con mayúscula, minúscula y número.</small>}<button disabled={busy}><LockKeyhole/>{busy?"Protegiendo…":cambiando?"Actualizar contraseña":recuperar?"Enviar enlace":registro?"Crear espacio privado":"Entrar"}</button></form>}{!registro&&!cambiando&&<button className="auth-switch" onClick={()=>{setRecuperar(!recuperar);setMfa(false);setError("");setMessage("")}}>{recuperar?"Volver al inicio de sesión":"Olvidé mi contraseña"}</button>}{registroPublico&&!recuperar&&!cambiando&&<button className="auth-switch" onClick={()=>{setRegistro(!registro);setMfa(false);setError("");setMessage("")}}>{registro?"Ya tengo una cuenta":"Crear una cuenta"}</button>}<div className="auth-trust"><ShieldCheck/><span><strong>Sesión protegida</strong>Cookie HttpOnly, vencimiento y cierre real.</span></div></section>
  </div></main>;
}
