import { FormEvent, useState } from "react";
import { CircleDollarSign, LockKeyhole, ShieldCheck } from "lucide-react";
import { financeApi } from "../api";

export default function AuthPage({ registro, onAuthenticated }: { registro: boolean; onAuthenticated: () => void }) {
  const [busy,setBusy]=useState(false), [error,setError]=useState("");
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{if(registro)await financeApi.registrarPropietario({nombre:String(data.get("nombre")),correo:String(data.get("correo")),password:String(data.get("password"))});else await financeApi.iniciarSesion({correo:String(data.get("correo")),password:String(data.get("password"))});onAuthenticated()}catch(err){setError(err instanceof Error?err.message:"No fue posible continuar")}finally{setBusy(false)}};
  return <main className="auth-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><section className="auth-card"><span className="auth-brand"><CircleDollarSign/></span><span className="eyebrow">FINANCEOS · ESPACIO PRIVADO</span><h1>{registro?"Protege tus finanzas":"Bienvenido de nuevo"}</h1><p>{registro?"Crea el propietario local. La contraseña se protegerá con Argon2id y nunca se almacenará en texto plano.":"Inicia sesión para acceder a tus datos financieros."}</p>{error&&<div className="error-banner">{error}</div>}<form onSubmit={submit}>{registro&&<label>Nombre<input name="nombre" minLength={2} maxLength={100} autoComplete="name" required/></label>}<label>Correo<input name="correo" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" minLength={registro?12:1} maxLength={128} autoComplete={registro?"new-password":"current-password"} required/></label>{registro&&<small>Usa mínimo 12 caracteres y una contraseña exclusiva para FinanceOS.</small>}<button disabled={busy}><LockKeyhole/>{busy?"Protegiendo…":registro?"Crear espacio privado":"Entrar"}</button></form><div className="auth-trust"><ShieldCheck/><span><strong>Sesión protegida</strong>Cookie HttpOnly, vencimiento y cierre real.</span></div></section></main>;
}
