import { FormEvent, useState } from "react";
import { CircleDollarSign, LockKeyhole, ShieldCheck } from "lucide-react";
import { financeApi } from "../api";

type Props={configuracionInicial:boolean;registroPublico:boolean;onAuthenticated:()=>void};

export default function AuthPage({configuracionInicial,registroPublico,onAuthenticated}:Props){
  const[registro,setRegistro]=useState(configuracionInicial);
  const[busy,setBusy]=useState(false),[error,setError]=useState("");
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{if(registro)await financeApi.registrarPropietario({nombre:String(data.get("nombre")),correo:String(data.get("correo")),password:String(data.get("password"))});else await financeApi.iniciarSesion({correo:String(data.get("correo")),password:String(data.get("password"))});onAuthenticated()}catch(err){setError(err instanceof Error?err.message:"No fue posible continuar")}finally{setBusy(false)}};
  const inicialLocal=configuracionInicial&&!registroPublico;
  return <main className="auth-page"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><section className="auth-card"><span className="auth-brand"><CircleDollarSign/></span><span className="eyebrow">FINANCEOS · ESPACIO PRIVADO</span><h1>{registro?(inicialLocal?"Configura FinanceOS":"Crea tu espacio"):"Bienvenido de nuevo"}</h1><p>{registro?(inicialLocal?"Crea el superadministrador de esta instalación privada.":"Regístrate como usuario. Tus datos financieros estarán separados de los demás."):"Inicia sesión para acceder únicamente a tus datos financieros."}</p>{error&&<div className="error-banner">{error}</div>}<form onSubmit={submit}>{registro&&<label>Nombre<input name="nombre" minLength={2} maxLength={100} autoComplete="name" required/></label>}<label>Correo<input name="correo" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" minLength={registro?12:1} maxLength={128} autoComplete={registro?"new-password":"current-password"} required/></label>{registro&&<small>Usa mínimo 12 caracteres y una contraseña exclusiva para FinanceOS.</small>}<button disabled={busy}><LockKeyhole/>{busy?"Protegiendo…":registro?"Crear espacio privado":"Entrar"}</button></form>{registroPublico&&<button className="auth-switch" onClick={()=>{setRegistro(!registro);setError("")}}>{registro?"Ya tengo una cuenta":"Crear una cuenta"}</button>}<div className="auth-trust"><ShieldCheck/><span><strong>Sesión protegida</strong>Cookie HttpOnly, vencimiento y cierre real.</span></div></section></main>;
}
