import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ChartNoAxesCombined, Plus, ShieldCheck, X } from "lucide-react";
import { Categoria, financeApi, Presupuesto } from "../api";

const now=new Date();const months=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
export default function BudgetsPage(){const[year,setYear]=useState(now.getFullYear());const[month,setMonth]=useState(now.getMonth()+1);const[items,setItems]=useState<Presupuesto[]>([]);const[categories,setCategories]=useState<Categoria[]>([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
const load=async()=>{const[b,c]=await Promise.all([financeApi.presupuestos(year,month),financeApi.categorias()]);setItems(b);setCategories(c.filter(x=>x.tipo.toLowerCase()==="gasto"))};useEffect(()=>{void load()},[year,month]);const totals=useMemo(()=>items.reduce((a,x)=>({budget:a.budget+x.valor,spent:a.spent+x.gastado}),{budget:0,spent:0}),[items]);
const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);try{await financeApi.crearPresupuesto({anio:year,mes:month,categoria_id:Number(d.get("categoria")),valor:Number(d.get("valor"))});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
return <section className="module-page"><div className="module-hero budget-hero"><div><span className="eyebrow text-cyan-200">PLANIFICACIÓN INTELIGENTE</span><h2>Presupuestos vivos</h2><p>Decide antes de gastar y observa el avance en tiempo real.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus size={17}/> Nuevo presupuesto</button><div className="module-orb"/></div>
<div className="period-control"><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select><select value={year} onChange={e=>setYear(Number(e.target.value))}>{[year-1,year,year+1].map(y=><option key={y}>{y}</option>)}</select><div><span>Planificado</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(totals.budget)}</strong></div><div><span>Consumido</span><strong>{totals.budget?Math.round(totals.spent/totals.budget*100):0}%</strong></div></div>
<div className="budget-grid">{items.map((item,index)=>{const pct=Math.min(item.valor?item.gastado/item.valor*100:0,100);const warning=pct>=80;return <article key={item.id} className="budget-card"><div className="flex items-start justify-between"><span className={`budget-symbol symbol-${index%4}`}><ChartNoAxesCombined/></span>{warning?<span className="warning-chip"><AlertTriangle/> Atención</span>:<span className="safe-chip"><ShieldCheck/> Saludable</span>}</div><h3>{item.categoria}</h3><div className="budget-values"><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(item.gastado)}</strong><span>de {new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(item.valor)}</span></div><div className="progress-track"><i style={{width:`${pct}%`}}/></div><p>{Math.round(pct)}% utilizado · {Math.max(0,item.valor-item.gastado).toLocaleString("es-CO")} disponibles</p></article>})}{!items.length&&<div className="empty-state budget-empty"><ChartNoAxesCombined/><h3>Este mes está libre</h3><p>Crea tu primer presupuesto para comenzar a planificar.</p></div>}</div>
{open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVO PRESUPUESTO</span><h3>Define tu límite</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div>{error&&<p className="form-error">{error}</p>}<label>Categoría<select name="categoria" required>{categories.map(x=><option value={x.id} key={x.id}>{x.icono} {x.nombre}</option>)}</select></label><label>Valor máximo<input name="valor" type="number" min="1" step="0.01" required/></label><button className="modal-submit" disabled={saving}><ChartNoAxesCombined/>{saving?"Guardando…":"Crear presupuesto"}</button></form></div>}</section>}
