import { useEffect, useState } from "react";
import { BellRing, CreditCard, Plus, Radar, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import { Categoria, Cuenta, Deteccion, financeApi, Tarjeta } from "../api";

const dinero=(v:number,m:string)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:m}).format(v);
export default function CardsPage({accounts,onChanged}:{accounts:Cuenta[];onChanged:()=>Promise<void>}){
 const [cards,setCards]=useState<Tarjeta[]>([]),[items,setItems]=useState<Deteccion[]>([]),[cats,setCats]=useState<Categoria[]>([]),[show,setShow]=useState(false),[payCard,setPayCard]=useState<Tarjeta|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({nombre:"",banco:"",ultimos_cuatro:"",tipo:"Debito",moneda:"COP",cuenta_id:accounts[0]?.id??0});
 const load=async()=>{const[t,d,c]=await Promise.all([financeApi.tarjetas(),financeApi.detecciones(),financeApi.categorias()]);setCards(t);setItems(d);setCats(c.filter(x=>x.tipo==="Gasto"));};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]); useEffect(()=>{if(!form.cuenta_id&&accounts[0])setForm(f=>({...f,cuenta_id:accounts[0].id}));},[accounts]);
 const create=async()=>{setBusy(true);setError("");try{await financeApi.crearTarjeta({...form,cuenta_id:form.tipo==="Credito"?undefined:Number(form.cuenta_id)});setShow(false);await Promise.all([load(),onChanged()]);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar")}finally{setBusy(false)}};
 const detect=async()=>{setBusy(true);try{const d=await financeApi.detectarOperacion(message,"Web");setMessage("");await load();if(d.duplicada)setError("El aviso ya existía y no se duplicó.");}catch(e){setError(e instanceof Error?e.message:"No se pudo analizar")}finally{setBusy(false)}};
 return <div className="space-y-5 pb-16"><section className="module-hero"><div><span className="eyebrow">MEDIOS DE PAGO · DETECCIÓN SEGURA</span><h2>Tarjetas inteligentes</h2><p>Relaciona cada tarjeta con su cuenta y confirma las compras antes de registrarlas.</p></div><button className="primary-action" onClick={()=>setShow(true)}><Plus size={17}/> Nueva tarjeta</button></section>
 {error&&<div className="error-banner">{error}</div>}<section className="grid gap-4 md:grid-cols-3"><article className="metric-card"><p>Tarjetas activas</p><strong>{cards.length}</strong><CreditCard/></article><article className="metric-card"><p>Por confirmar</p><strong>{items.length}</strong><BellRing/></article><article className="metric-card"><p>Protección</p><strong>Sin duplicados</strong><ShieldCheck/></article></section>
 <section className="panel-card p-5"><div className="panel-heading"><div><span className="eyebrow">CAPTURA WEB</span><h2>Pegar aviso bancario</h2></div><Radar className="text-cyan-300"/></div><textarea className="modern-input mt-4 min-h-28 w-full" placeholder="Compra por COP $75.900 en ADIDAS con tarjeta débito terminada en 1234..." value={message} onChange={e=>setMessage(e.target.value)}/><button className="primary-action mt-3" disabled={busy||!message.trim()} onClick={()=>void detect()}><Sparkles size={17}/> Analizar aviso</button></section>
 <section><div className="panel-heading"><div><span className="eyebrow">BILLETERA</span><h2>Medios registrados</h2></div></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map((c,i)=><article key={c.id} className={`account-tile relative min-h-52 logo-${i%4}`}><div className="flex items-start justify-between"><span className="account-logo"><CreditCard/></span><span className="currency-chip">{c.moneda}</span></div><div><span className="eyebrow">{c.tipo} · {c.banco||"Entidad"}</span><p className="mt-1 text-xl font-bold">{c.nombre}</p><strong>•••• {c.ultimos_cuatro}</strong><small className="mt-2 block text-white/45">{c.tipo==="Credito"?`Deuda: ${dinero(Math.abs(Math.min(c.saldo,0)),c.moneda)}`:`Vinculada a ${c.cuenta}`}</small></div><div className="absolute bottom-4 right-4 flex gap-2">{c.tipo==="Credito"&&c.saldo<0&&<button className="ghost-action h-9" onClick={()=>setPayCard(c)}>Pagar</button>}<button className="text-white/40 hover:text-rose-300" onClick={async()=>{await financeApi.eliminarTarjeta(c.id);await load()}}><Trash2 size={17}/></button></div></article>)}</div></section>
 <section className="panel-card p-5"><div className="panel-heading"><div><span className="eyebrow">BANDEJA</span><h2>Compras por confirmar</h2></div><span className="live-pill"><i/> {items.length} pendientes</span></div><div className="mt-4 space-y-3">{items.length===0?<div className="insight-strip"><ShieldCheck/><p>No hay compras pendientes.</p></div>:items.map(d=><Detection key={d.id} item={d} cards={cards} accounts={accounts} cats={cats} busy={busy} refresh={async()=>{await load();await onChanged()}} setError={setError}/>)}</div></section>
 {show&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setShow(false)}/><div className="modern-modal"><button className="absolute right-5 top-5" onClick={()=>setShow(false)}><X/></button><span className="eyebrow">NUEVO MEDIO</span><h3>Vincular tarjeta</h3><div className="form-grid"><Field label="Nombre"><input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Banco"><input value={form.banco} onChange={e=>setForm({...form,banco:e.target.value})}/></Field><Field label="Últimos 4"><input maxLength={4} value={form.ultimos_cuatro} onChange={e=>setForm({...form,ultimos_cuatro:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Tipo"><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option value="Debito">Débito</option><option value="Credito">Crédito</option></select></Field>{form.tipo==="Debito"&&<Field label="Cuenta bancaria"><select value={form.cuenta_id} onChange={e=>setForm({...form,cuenta_id:Number(e.target.value)})}>{accounts.filter(a=>a.moneda===form.moneda&&a.tipo.toLowerCase()!=="tarjeta de credito").map(a=><option key={a.id} value={a.id}>{a.nombre} ({a.moneda})</option>)}</select></Field>}<Field label="Moneda"><select value={form.moneda} onChange={e=>setForm({...form,moneda:e.target.value})}><option>COP</option><option>USD</option><option>EUR</option></select></Field></div><p className="mt-4 text-xs text-white/45">{form.tipo==="Credito"?"FinanceOS creará automáticamente una cuenta de deuda separada. Las compras no descontarán tu cuenta bancaria.":"Las compras descontarán directamente la cuenta bancaria vinculada."}</p><button className="modal-submit" disabled={busy||form.ultimos_cuatro.length!==4||!form.nombre} onClick={()=>void create()}>Guardar tarjeta</button></div></div>}
 {payCard&&<PaymentModal card={payCard} accounts={accounts.filter(a=>a.id!==payCard.cuenta_id&&a.moneda===payCard.moneda)} busy={busy} close={()=>setPayCard(null)} pay={async(account,value)=>{setBusy(true);setError("");try{await financeApi.pagarTarjeta(payCard.id,{cuenta_origen_id:account,valor:value,fecha:new Date().toISOString().slice(0,10),descripcion:`Pago de ${payCard.nombre}`});setPayCard(null);await Promise.all([load(),onChanged()])}catch(e){setError(e instanceof Error?e.message:"No se pudo pagar")}finally{setBusy(false)}}}/>}</div>
}
function Detection({item,cards,accounts,cats,busy,refresh,setError}:{item:Deteccion;cards:Tarjeta[];accounts:Cuenta[];cats:Categoria[];busy:boolean;refresh:()=>Promise<void>;setError:(s:string)=>void}){const[c,setC]=useState(cats[0]?.id??0),[t,setT]=useState(item.tarjeta_id??0),[a,setA]=useState(0);const confirm=async()=>{try{await financeApi.confirmarDeteccion(item.id,{categoria_id:c,tarjeta_id:t||undefined,cuenta_id:a||undefined,descripcion:item.comercio});await refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo confirmar")}};return <article className="detection-row"><div className="detection-icon"><BellRing/></div><div className="min-w-0 flex-1"><strong>{item.comercio}</strong><p className="text-xl font-bold">{dinero(item.valor,item.moneda)}</p><small>{item.tipo_sugerido??"Tipo por definir"} {item.ultimos_cuatro?`· •••• ${item.ultimos_cuatro}`:""}</small></div><div className="grid min-w-[280px] gap-2 sm:grid-cols-2"><select value={c} onChange={e=>setC(Number(e.target.value))}>{cats.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><select value={t} onChange={e=>setT(Number(e.target.value))}><option value="0">Sin tarjeta</option>{cards.map(x=><option key={x.id} value={x.id}>{x.nombre} •{x.ultimos_cuatro}</option>)}</select>{!t&&<select value={a} onChange={e=>setA(Number(e.target.value))}><option value="0">Seleccionar cuenta</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select>}<button className="primary-action justify-center" disabled={busy||!c||(!t&&!a)} onClick={()=>void confirm()}>Confirmar</button><button className="ghost-action justify-center" onClick={async()=>{await financeApi.descartarDeteccion(item.id);await refresh()}}>Descartar</button></div></article>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
function PaymentModal({card,accounts,busy,close,pay}:{card:Tarjeta;accounts:Cuenta[];busy:boolean;close:()=>void;pay:(account:number,value:number)=>Promise<void>}){const[account,setAccount]=useState(accounts[0]?.id??0),[value,setValue]=useState(Math.abs(Math.min(card.saldo,0)));return <div className="modal-layer"><button className="modal-backdrop" onClick={close}/><div className="modern-modal"><button className="absolute right-5 top-5" onClick={close}><X/></button><span className="eyebrow">PAGO DE TARJETA</span><h3>{card.nombre}</h3><p className="text-white/55">Deuda pendiente: <strong className="text-white">{dinero(Math.abs(Math.min(card.saldo,0)),card.moneda)}</strong></p><Field label="Pagar desde"><select value={account} onChange={e=>setAccount(Number(e.target.value))}>{accounts.map(a=><option key={a.id} value={a.id}>{a.nombre} · {dinero(a.saldo,a.moneda)}</option>)}</select></Field><Field label="Valor"><input type="number" min="0.01" max={Math.abs(card.saldo)} step="0.01" value={value} onChange={e=>setValue(Number(e.target.value))}/></Field><p className="mt-3 text-xs text-white/45">Este pago será una transferencia interna: reduce tu cuenta bancaria y también la deuda, sin crear un gasto duplicado.</p><button className="modal-submit" disabled={busy||!account||value<=0} onClick={()=>void pay(account,value)}>Confirmar pago</button></div></div>}
