import { FormEvent, useEffect, useMemo, useState } from "react";
import { Edit3, Plus, Search, Sparkles, Tags, Trash2, X } from "lucide-react";
import { Categoria, financeApi } from "../api";
import ConfirmDialog from "../components/ConfirmDialog";

const empty = { nombre: "", tipo: "Gasto", color: "#6f62f5", icono: "🏷️", grupo: "Otros", orden: 0, activa: true };

export default function CategoriesPage() {
  const [items,setItems]=useState<Categoria[]>([]), [search,setSearch]=useState(""), [open,setOpen]=useState(false);
  const [editing,setEditing]=useState<Categoria|null>(null), [deleting,setDeleting]=useState<Categoria|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const load=async()=>setItems(await financeApi.categorias());
  useEffect(()=>{void load().catch(()=>setError("No fue posible cargar las categorías."))},[]);
  const visible=useMemo(()=>items.filter(c=>`${c.nombre} ${c.grupo} ${c.tipo}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const groups=useMemo(()=>Array.from(new Set(visible.map(c=>`${c.tipo}·${c.grupo||"Otros"}`))),[visible]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);const body={nombre:String(d.get("nombre")),tipo:String(d.get("tipo")),color:String(d.get("color")),icono:String(d.get("icono")),grupo:String(d.get("grupo")),orden:Number(d.get("orden")),activa:true};try{editing?await financeApi.actualizarCategoria(editing.id,body):await financeApi.crearCategoria(body);await load();setOpen(false);setEditing(null)}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setBusy(false)}};
  const erase=async()=>{if(!deleting)return;setBusy(true);try{await financeApi.eliminarCategoria(deleting.id);setDeleting(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible eliminar") }finally{setBusy(false)}};
  return <section className="module-page">
    <div className="module-hero category-hero"><div><span className="eyebrow text-cyan-200">CÓMO USAS TU DINERO</span><h2>Categorías de ingresos y gastos</h2><p>Clasifica los movimientos para saber de dónde viene tu dinero y en qué lo estás gastando.</p></div><button className="primary-action" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/> Nueva categoría</button><div className="module-orb"/></div>
    <div className="module-stats"><div><span>Total</span><strong>{items.length}</strong></div><div><span>Ingresos</span><strong>{items.filter(x=>x.tipo==="Ingreso").length}</strong></div><div><span>Gastos</span><strong>{items.filter(x=>x.tipo==="Gasto").length}</strong></div></div>
    {error&&<p className="form-error">{error}</p>}
    <label className="module-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, grupo o tipo…"/></label>
    <div className="category-groups">{groups.map(group=>{const [type,name]=group.split("·");return <section key={group}><div className="category-heading"><div><span>{type}</span><h3>{name}</h3></div><small>{visible.filter(c=>`${c.tipo}·${c.grupo||"Otros"}`===group).length} categorías</small></div><div className="category-grid">{visible.filter(c=>`${c.tipo}·${c.grupo||"Otros"}`===group).map(item=><article className="category-card" key={item.id} style={{"--category-color":item.color} as React.CSSProperties}><span className="category-icon">{item.icono||"🏷️"}</span><div><strong>{item.nombre}</strong><small>{item.activa?"Activa":"Inactiva"}</small></div><div className="category-actions"><button title="Editar" onClick={()=>{setEditing(item);setOpen(true)}}><Edit3/></button><button title="Eliminar" onClick={()=>setDeleting(item)}><Trash2/></button></div></article>)}</div></section>})}</div>
    <div className="module-insight"><Sparkles/><div><strong>Clasificación consistente</strong><p>Las categorías alimentan movimientos, presupuestos, reportes y el Dashboard.</p></div></div>
    {deleting&&<ConfirmDialog title={`Eliminar ${deleting.nombre}`} description="Esta categoría desaparecerá del catálogo. Si tiene movimientos relacionados, FinanceOS protegerá la información y cancelará la eliminación." busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void erase()}/>} 
    {open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">{editing?"EDITAR":"NUEVA"} CATEGORÍA</span><h3>{editing?"Actualiza su identidad":"Organiza tu dinero"}</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label>Nombre<input name="nombre" required defaultValue={editing?.nombre||empty.nombre}/></label><label>Grupo<input name="grupo" required defaultValue={editing?.grupo||empty.grupo}/></label><label>Tipo<select name="tipo" defaultValue={editing?.tipo||empty.tipo}><option>Gasto</option><option>Ingreso</option><option>Transferencia</option><option>Ahorro</option><option>Inversión</option></select></label><label>Icono<input name="icono" defaultValue={editing?.icono||empty.icono}/></label><label>Color<input name="color" type="color" defaultValue={editing?.color||empty.color}/></label><label>Orden<input name="orden" type="number" defaultValue={empty.orden}/></label></div><button className="modal-submit" disabled={busy}><Tags/>{busy?"Guardando…":"Guardar categoría"}</button></form></div>}
  </section>;
}
