import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, Globe2, RefreshCw, Sparkles } from "lucide-react";
import { Conversion, financeApi, TasaCambio } from "../api";

const money=(value:number,currency:string)=>new Intl.NumberFormat("es-CO",{style:"currency",currency,maximumFractionDigits:2}).format(value);
export default function CurrenciesPage(){
 const [rates,setRates]=useState<TasaCambio[]>([]),[result,setResult]=useState<Conversion|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>setRates(await financeApi.tasas()); useEffect(()=>{void load().catch(()=>setError("No fue posible cargar las tasas."))},[]);
 const currencies=useMemo(()=>Array.from(new Set(["COP","USD","EUR","GBP","JPY","BRL","MXN","CAD","AUD",...rates.flatMap(r=>[r.moneda_origen,r.moneda_destino])])),[rates]);
 const update=async()=>{setBusy(true);setError("");try{await financeApi.actualizarTasas();await load()}catch(e){setError(e instanceof Error?e.message:"No fue posible actualizar") }finally{setBusy(false)}};
 const convert=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);try{setResult(await financeApi.convertir(Number(d.get("valor")),String(d.get("origen")),String(d.get("destino"))))}catch(err){setError(err instanceof Error?err.message:"No fue posible convertir") }finally{setBusy(false)}};
 const usdCop=rates.find(r=>r.moneda_origen==="USD"&&r.moneda_destino==="COP");
 return <section className="module-page"><div className="module-hero currency-hero"><div><span className="eyebrow text-cyan-200">CONVERSIÓN A PESOS</span><h2>Monedas y tasas de cambio</h2><p>Conserva cada valor en su moneda original y usa estas tasas para mostrar el patrimonio consolidado en COP.</p></div><button className="primary-action" onClick={()=>void update()} disabled={busy}><RefreshCw className={busy?"animate-spin":""}/>{busy?"Actualizando…":"Actualizar tasas"}</button><div className="module-orb"/></div>
 <div className="currency-highlight"><div><span>TASA DE REFERENCIA</span><h3>USD <ArrowRightLeft/> COP</h3><strong>{usdCop?new Intl.NumberFormat("es-CO",{maximumFractionDigits:2}).format(usdCop.tasa):"—"}</strong><small>{usdCop?`Actualizada ${new Date(usdCop.fecha_actualizacion).toLocaleString("es-CO")}`:"Actualiza las tasas para comenzar"}</small></div><Globe2/></div>
 {error&&<p className="form-error">{error}</p>}<form className="converter-card" onSubmit={convert}><div><span className="eyebrow">CONVERSOR GLOBAL</span><h3>Convierte al instante</h3></div><label>Valor<input name="valor" type="number" min="0.01" step="0.01" defaultValue="100"/></label><label>Origen<select name="origen" defaultValue="USD">{currencies.map(x=><option key={x}>{x}</option>)}</select></label><ArrowRightLeft className="converter-arrow"/><label>Destino<select name="destino" defaultValue="COP">{currencies.map(x=><option key={x}>{x}</option>)}</select></label><button className="modal-submit" disabled={busy}>Convertir</button>{result&&<div className="conversion-result"><span>RESULTADO</span><strong>{money(result.valor_convertido,result.destino)}</strong><small>{money(result.valor_origen,result.origen)}</small></div>}</form>
 <div className="rates-panel"><div className="panel-heading"><div><span className="eyebrow">TASAS DISPONIBLES</span><h2>Mercado almacenado</h2></div><small>{rates.length} pares</small></div><div className="rates-grid">{rates.slice(0,18).map(r=><article key={r.id}><div><span>{r.moneda_origen}</span><ArrowRightLeft/><span>{r.moneda_destino}</span></div><strong>{new Intl.NumberFormat("es-CO",{maximumFractionDigits:4}).format(r.tasa)}</strong><small>{r.fuente||"FinanceOS"}</small></article>)}</div></div>
 <div className="module-insight"><Sparkles/><div><strong>Consolidación segura</strong><p>FinanceOS mantiene cada movimiento en su moneda original y usa estas tasas para el Dashboard en COP.</p></div></div></section>;
}
