import { FormEvent, ReactNode, useEffect, useState } from "react";
import { CalendarDays, CreditCard, Flag, Plus, Rocket, Sparkles, Target, Trash2, X } from "lucide-react";
import { Categoria, Cuenta, financeApi, Meta } from "../api";
import ConfirmDialog from "../components/ConfirmDialog";

export default function GoalsPage(){
 const [items,setItems]=useState<Meta[]>([]),[accounts,setAccounts]=useState<Cuenta[]>([]),[categories,setCategories]=useState<Categoria[]>([]),[open,setOpen]=useState(false),[contribute,setContribute]=useState<Meta|null>(null),[pay,setPay]=useState<Meta|null>(null),[deleting,setDeleting]=useState<Meta|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{const[m,a,c]=await Promise.all([financeApi.metas(),financeApi.cuentas(),financeApi.categorias()]);setItems(m);setAccounts(a);setCategories(c.filter(x=>x.tipo==="Gasto"))};useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const d=new FormData(e.currentTarget);try{await financeApi.crearMeta({nombre:String(d.get("nombre")),objetivo:Number(d.get("objetivo")),moneda:String(d.get("moneda")),fecha_limite:String(d.get("fecha"))||null,descripcion:String(d.get("descripcion")||"")});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
 const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!contribute)return;setSaving(true);const d=new FormData(e.currentTarget);try{await financeApi.aportarMeta(contribute.id,{fecha:String(d.get("fecha")),valor:Number(d.get("valor")),descripcion:String(d.get("descripcion")||"")});setContribute(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible registrar") }finally{setSaving(false)}};
 const registerPayment=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!pay)return;setSaving(true);const d=new FormData(e.currentTarget);try{await financeApi.pagarMeta(pay.id,{fecha:String(d.get("fecha")),valor:Number(d.get("valor")),descripcion:String(d.get("descripcion")||`Pago de ${pay.nombre}`),cuenta_id:Number(d.get("cuenta")),categoria_id:Number(d.get("categoria")),observaciones:String(d.get("observaciones")||"")});setPay(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible registrar el pago") }finally{setSaving(false)}};
 const erase=async()=>{if(!deleting)return;setSaving(true);try{await financeApi.eliminarMeta(deleting.id);setDeleting(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible eliminar") }finally{setSaving(false)}};
 return <section className="module-page"><div className="module-hero goals-hero"><div><span className="eyebrow text-violet-200">PARA QUÉ ESTÁS AHORRANDO</span><h2>Metas de ahorro y pagos</h2><p>Aportar aumenta el progreso; pagar descuenta dinero de una cuenta y registra el movimiento correspondiente.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus/> Nueva meta</button><div className="module-orb"/></div>{error&&<p className="form-error">{error}</p>}
 <div className="goals-grid">{items.map((goal,index)=>{const pct=Math.min(goal.porcentaje,100),fmt=(v:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:goal.moneda,maximumFractionDigits:0}).format(v);return <article className="goal-card" key={goal.id}><div className="goal-top"><span className={`goal-icon goal-${index%4}`}><Target/></span><button className="goal-delete" title="Eliminar meta" onClick={()=>setDeleting(goal)}><Trash2/></button></div><div><h3>{goal.nombre}</h3><p>{goal.descripcion||"Una meta de FinanceOS"}</p></div><div className="goal-ring" style={{background:`conic-gradient(#7767f5 ${pct*3.6}deg,rgba(255,255,255,.06) 0)`}}><i><strong>{Math.round(pct)}%</strong><span>pagado</span></i></div><div className="goal-numbers"><div><span>Objetivo</span><strong>{fmt(goal.objetivo)}</strong></div><div><span>Pendiente</span><strong>{fmt(goal.pendiente)}</strong></div></div>{goal.fecha_limite&&<p className="goal-date"><CalendarDays/> {new Date(`${goal.fecha_limite}T00:00:00`).toLocaleDateString("es-CO")}</p>}<div className="goal-buttons"><button className="goal-action" onClick={()=>setContribute(goal)}><Rocket/> Aportar</button><button className="goal-action pay" onClick={()=>setPay(goal)}><CreditCard/> Registrar pago</button></div></article>})}{!items.length&&<div className="empty-state goals-empty"><Flag/><h3>Tu próxima meta empieza aquí</h3></div>}</div>
 {deleting&&<ConfirmDialog title={`Eliminar ${deleting.nombre}`} description={`La meta tiene aportes por ${deleting.aportado} y pagos por ${deleting.pagado}. Se eliminará la meta y todo su historial asociado.`} busy={saving} onCancel={()=>setDeleting(null)} onConfirm={()=>void erase()}/>} 
 {open&&<GoalModal title="Nueva meta" onClose={()=>setOpen(false)} onSubmit={create} saving={saving}><label>Nombre<input name="nombre" required/></label><div className="form-grid"><label>Objetivo<input name="objetivo" type="number" min="1" step=".01" required/></label><label>Moneda<select name="moneda"><option>COP</option><option>USD</option><option>EUR</option></select></label></div><label>Fecha objetivo<input name="fecha" type="date"/></label><label>Descripción<input name="descripcion"/></label></GoalModal>}
 {contribute&&<GoalModal title={`Aportar a ${contribute.nombre}`} onClose={()=>setContribute(null)} onSubmit={add} saving={saving}><div className="form-grid"><label>Fecha<input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Valor ({contribute.moneda})<input name="valor" type="number" min=".01" step=".01" required/></label></div><label>Nota<input name="descripcion"/></label></GoalModal>}
 {pay&&<GoalModal title={`Pagar ${pay.nombre}`} onClose={()=>setPay(null)} onSubmit={registerPayment} saving={saving}><div className="form-grid"><label>Fecha<input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Valor ({pay.moneda})<input name="valor" type="number" min=".01" max={pay.pendiente} step=".01" required/></label><label>Cuenta<select name="cuenta">{accounts.map(x=><option value={x.id} key={x.id}>{x.nombre} ({x.moneda})</option>)}</select></label><label>Categoría<select name="categoria">{categories.map(x=><option value={x.id} key={x.id}>{x.nombre}</option>)}</select></label></div><label>Descripción<input name="descripcion" defaultValue={`Pago de ${pay.nombre}`}/></label><label>Observaciones<input name="observaciones"/></label></GoalModal>}
 </section>;
}

function GoalModal({title,onClose,onSubmit,saving,children}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;saving:boolean;children:ReactNode}){return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose}/><form className="modern-modal" onSubmit={onSubmit}><div className="flex items-start justify-between"><div><span className="eyebrow">GESTIÓN DE META</span><h3>{title}</h3></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div>{children}<button className="modal-submit" disabled={saving}><Sparkles/>{saving?"Procesando…":"Confirmar"}</button></form></div>}
