import { FormEvent, useEffect, useState } from "react";
import { CalendarDays, Flag, Plus, Rocket, Sparkles, Target, X } from "lucide-react";
import { financeApi, Meta } from "../api";

export default function GoalsPage(){const[items,setItems]=useState<Meta[]>([]);const[open,setOpen]=useState(false);const[contribute,setContribute]=useState<Meta|null>(null);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const load=async()=>setItems(await financeApi.metas());useEffect(()=>{void load()},[]);
const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);try{await financeApi.crearMeta({nombre:String(d.get("nombre")),objetivo:Number(d.get("objetivo")),moneda:String(d.get("moneda")),fecha_limite:String(d.get("fecha"))||null,descripcion:String(d.get("descripcion")||"")});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!contribute)return;setSaving(true);setError("");const d=new FormData(e.currentTarget);try{await financeApi.aportarMeta(contribute.id,{fecha:String(d.get("fecha")),valor:Number(d.get("valor")),descripcion:String(d.get("descripcion")||"")});setContribute(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible registrar el aporte") }finally{setSaving(false)}};
return <section className="module-page"><div className="module-hero goals-hero"><div><span className="eyebrow text-violet-200">VISIÓN · PROPÓSITO</span><h2>Metas que avanzan</h2><p>Convierte planes importantes en progreso financiero visible.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus/> Nueva meta</button><div className="module-orb"/></div>
<div className="goals-grid">{items.map((goal,index)=>{const pct=Math.min(goal.porcentaje,100);return <article className="goal-card" key={goal.id}><div className="goal-top"><span className={`goal-icon goal-${index%4}`}><Target/></span><span className="goal-percent">{Math.round(pct)}%</span></div><div><h3>{goal.nombre}</h3><p>{goal.descripcion||"Una meta de FinanceOS"}</p></div><div className="goal-ring" style={{background:`conic-gradient(#7767f5 ${pct*3.6}deg,rgba(255,255,255,.06) 0)`}}><i><strong>{Math.round(pct)}%</strong><span>avance</span></i></div><div className="goal-numbers"><div><span>Objetivo</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:goal.moneda,maximumFractionDigits:0}).format(goal.objetivo)}</strong></div><div><span>Pendiente</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:goal.moneda,maximumFractionDigits:0}).format(goal.pendiente)}</strong></div></div>{goal.fecha_limite&&<p className="goal-date"><CalendarDays/> {new Date(`${goal.fecha_limite}T00:00:00`).toLocaleDateString("es-CO",{day:"numeric",month:"long",year:"numeric"})}</p>}<button className="goal-action" onClick={()=>setContribute(goal)}><Rocket/> Registrar aporte</button></article>})}{!items.length&&<div className="empty-state goals-empty"><Flag/><h3>Tu próxima meta empieza aquí</h3><p>Define un objetivo y sigue su progreso.</p></div>}</div>
{open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={create}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVA META</span><h3>Diseña tu próximo logro</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div>{error&&<p className="form-error">{error}</p>}<label>Nombre<input name="nombre" required placeholder="Ej: Viaje a Japón"/></label><div className="form-grid"><label>Valor objetivo<input name="objetivo" type="number" min="1" step="0.01" required/></label><label>Moneda<select name="moneda"><option>COP</option><option>USD</option><option>EUR</option></select></label></div><label>Fecha objetivo<input name="fecha" type="date"/></label><label>Descripción<input name="descripcion" placeholder="¿Por qué es importante para ti?"/></label><button className="modal-submit" disabled={saving}><Sparkles/>{saving?"Guardando…":"Crear meta"}</button></form></div>}
{contribute&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setContribute(null)}/><form className="modern-modal" onSubmit={add}><div className="flex items-start justify-between"><div><span className="eyebrow">APORTE A META</span><h3>{contribute.nombre}</h3></div><button type="button" className="icon-button" onClick={()=>setContribute(null)}><X/></button></div>{error&&<p className="form-error">{error}</p>}<div className="form-grid"><label>Fecha<input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Valor ({contribute.moneda})<input name="valor" type="number" min="0.01" step="0.01" required/></label></div><label>Nota<input name="descripcion" placeholder="Ej: Ahorro de esta quincena"/></label><button className="modal-submit" disabled={saving}><Rocket/>{saving?"Registrando…":"Registrar aporte"}</button></form></div>}</section>}
