import { FormEvent, useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, ChartCandlestick, Plus, TrendingUp, X } from "lucide-react";
import { financeApi, Portafolio } from "../api";

const cop=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
export default function InvestmentsPage(){const[data,setData]=useState<Portafolio|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const load=async()=>setData(await financeApi.inversiones());useEffect(()=>{void load()},[]);
const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);try{await financeApi.crearInversion({activo:String(d.get("activo")),tipo:String(d.get("tipo")),cantidad:Number(d.get("cantidad")),precio_compra:Number(d.get("compra")),precio_actual:Number(d.get("actual")),broker:String(d.get("broker")||""),moneda:String(d.get("moneda")),valores_totales:d.get("totales")==="on"});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
return <section className="module-page"><div className="investment-head"><div><span className="eyebrow text-cyan-200">WEALTH · PORTAFOLIO</span><h2>Capital en movimiento</h2><p>Rendimiento consolidado en pesos, posiciones conservadas en su moneda original.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus/> Nueva posición</button><div className="market-wave"/></div>
<div className="portfolio-summary"><article><span>Valor del portafolio</span><strong>{cop.format(data?.valor_total_cop??0)}</strong><small><TrendingUp/> Consolidado en COP</small></article><article><span>Capital invertido</span><strong>{cop.format(data?.costo_total_cop??0)}</strong><small><BriefcaseBusiness/> Base de costo</small></article><article className={(data?.ganancia_total_cop??0)>=0?"positive":"negative"}><span>Ganancia total</span><strong>{cop.format(data?.ganancia_total_cop??0)}</strong><small>{(data?.ganancia_total_cop??0)>=0?<ArrowUpRight/>:<ArrowDownRight/>}{(data?.rentabilidad??0).toFixed(2)}% de rentabilidad</small></article></div>
<div className="positions-grid">{data?.posiciones.map((item,index)=><article className="position-card" key={item.id}><div className="flex items-start justify-between"><span className={`ticker ticker-${index%4}`}>{item.activo.slice(0,4).toUpperCase()}</span><span className={item.ganancia>=0?"return positive":"return negative"}>{item.ganancia>=0?"+":""}{item.rentabilidad.toFixed(2)}%</span></div><div><p>{item.tipo} · {item.broker||"Sin broker"}</p><h3>{item.activo}</h3></div><div className="position-value"><span>Valor actual</span><strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:item.moneda}).format(item.valor)}</strong></div><div className="position-foot"><span>{item.cantidad.toLocaleString("es-CO")} unidades</span><strong className={item.ganancia>=0?"positive":"negative"}>{item.ganancia>=0?"+":""}{new Intl.NumberFormat("es-CO",{style:"currency",currency:item.moneda}).format(item.ganancia)}</strong></div></article>)}{!data?.posiciones.length&&<div className="empty-state positions-empty"><ChartCandlestick/><h3>Tu portafolio comienza aquí</h3><p>Registra tu primera inversión para seguir su rendimiento.</p></div>}</div>
{open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVA POSICIÓN</span><h3>Registra una inversión</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div>{error&&<p className="form-error">{error}</p>}<div className="form-grid"><label>Activo<input name="activo" required placeholder="Ej: VOO"/></label><label>Tipo<select name="tipo"><option>ETF</option><option>Acción</option><option>Criptomoneda</option><option>CDT</option><option>Fondo</option></select></label></div><div className="form-grid"><label>Cantidad<input name="cantidad" type="number" min="0.00000001" step="any" required/></label><label>Moneda<select name="moneda"><option>USD</option><option>COP</option><option>EUR</option></select></label></div><div className="form-grid"><label>Precio o costo de compra<input name="compra" type="number" min="0.01" step="any" required/></label><label>Precio o valor actual<input name="actual" type="number" min="0.01" step="any" required/></label></div><label>Broker<input name="broker" placeholder="Ej: Hapi"/></label><label className="check-label"><input name="totales" type="checkbox"/> Los valores son totales reportados por el broker</label><button className="modal-submit" disabled={saving}><ChartCandlestick/>{saving?"Guardando…":"Agregar al portafolio"}</button></form></div>}</section>}
