import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, Plus, ReceiptText, Search, X } from "lucide-react";
import { Categoria, Cuenta, financeApi, Movimiento } from "../api";

export default function MovementsPage({accounts}:{accounts:Cuenta[]}){
  const [items,setItems]=useState<Movimiento[]>([]);const [categories,setCategories]=useState<Categoria[]>([]);const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const load=async()=>{const[m,c]=await Promise.all([financeApi.movimientos(),financeApi.categorias()]);setItems(m);setCategories(c)};useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>items.filter(x=>`${x.descripcion} ${x.categoria} ${x.cuenta}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);try{await financeApi.crearMovimiento({fecha:String(d.get("fecha")),descripcion:String(d.get("descripcion")),valor:Number(d.get("valor")),cuenta_id:Number(d.get("cuenta")),categoria_id:Number(d.get("categoria")),observaciones:String(d.get("observaciones")??"")});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
  return <section className="module-page"><div className="module-hero movements-hero"><div><span className="eyebrow text-violet-200">ACTIVIDAD FINANCIERA</span><h2>Movimientos sin ruido</h2><p>Cada ingreso y gasto conserva la moneda de su cuenta.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><Plus size={17}/> Nuevo movimiento</button><div className="module-orb"/></div>
    <div className="movement-toolbar"><div className="movement-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por descripción, categoría o cuenta"/></div><span>{filtered.length} movimientos</span></div>
    <div className="movement-list">{filtered.map(item=>{const income=item.tipo.toLowerCase()==="ingreso";return <article key={item.id}><span className={income?"movement-icon income":"movement-icon expense"}>{income?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div className="movement-main"><strong>{item.descripcion||item.categoria}</strong><p>{item.categoria} · {item.cuenta}</p></div><time>{new Date(`${item.fecha}T00:00:00`).toLocaleDateString("es-CO",{day:"2-digit",month:"short"})}</time><strong className={income?"amount income":"amount expense"}>{income?"+":"−"}{new Intl.NumberFormat("es-CO",{style:"currency",currency:item.moneda}).format(Math.abs(item.valor))}</strong></article>})}{!filtered.length&&<div className="empty-state"><ReceiptText/><h3>No hay movimientos para mostrar</h3><p>Crea uno nuevo o cambia la búsqueda.</p></div>}</div>
    {open&&<div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={()=>setOpen(false)}/><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVO MOVIMIENTO</span><h3>Registra una operación</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{error&&<p className="form-error">{error}</p>}<div className="form-grid"><label>Fecha<input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required/></label></div><label>Descripción<input name="descripcion" placeholder="Ej: Mercado de la semana" required/></label><div className="form-grid"><label>Cuenta<select name="cuenta" required>{accounts.map(x=><option key={x.id} value={x.id}>{x.nombre} ({x.moneda})</option>)}</select></label><label>Categoría<select name="categoria" required>{categories.map(x=><option key={x.id} value={x.id}>{x.tipo}: {x.nombre}</option>)}</select></label></div><label>Observaciones<input name="observaciones" placeholder="Opcional"/></label><button className="modal-submit" disabled={saving}><ReceiptText size={17}/>{saving?"Guardando…":"Guardar movimiento"}</button></form></div>}
  </section>
}
