import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, Camera, Edit3, FileUp, LoaderCircle, Paperclip, Plus, ReceiptText, Search, Trash2, X } from "lucide-react";
import { Categoria, Cuenta, financeApi, GastoRecurrente, Movimiento } from "../api";
import ConfirmDialog from "../components/ConfirmDialog";

type ReceiptDraft={fecha:string;descripcion:string;valor:string;observaciones:string;texto:string;huella?:string};
const today=()=>new Date().toISOString().slice(0,10);
const normalized=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();

function extractReceipt(text:string):ReceiptDraft{
 const normalizedText=text.replace(/([\d.,])[\s\u00a0]+(?=[\d.,])/g,"$1");
 const lines=normalizedText.split(/\r?\n/).map(x=>x.trim()).filter(x=>x.length>2);
 const dateMatch=normalizedText.match(/\b(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})\b/)||normalizedText.match(/\b(\d{1,2})[-/.](\d{1,2})[-/.](20\d{2})\b/);
 let fecha=today();if(dateMatch)fecha=dateMatch[1].length===4?`${dateMatch[1]}-${dateMatch[2].padStart(2,"0")}-${dateMatch[3].padStart(2,"0")}`:`${dateMatch[3]}-${dateMatch[2].padStart(2,"0")}-${dateMatch[1].padStart(2,"0")}`;
 const numeric=(value:string)=>{const clean=value.replace(/[^\d.,]/g,"");const lastComma=clean.lastIndexOf(","),lastDot=clean.lastIndexOf("."),decimal=Math.max(lastComma,lastDot);if(decimal>=0&&clean.length-decimal-1===2){const integer=clean.slice(0,decimal).replace(/[.,]/g,"");return Number(`${integer}.${clean.slice(decimal+1)}`)}return Number(clean.replace(/[.,]/g,""))};
 const patterns=[
  /total\s*\(\s*cop\s*\)\s*:?\s*\$?\s*([\d.,]+)/gi,
  /total\s+a\s+pagar\s*:?\s*\$?\s*([\d.,]+)/gi,
  /(?:^|\n)\s*total\s*:?\s*\$?\s*([\d.,]+)/gi,
  /importe\s+total\s*:?\s*\$?\s*([\d.,]+)/gi,
 ];
 let valor:number|undefined;for(const pattern of patterns){const candidates=Array.from(normalizedText.matchAll(pattern)).map(match=>numeric(match[1])).filter(number=>Number.isFinite(number)&&number>0);if(candidates.length){valor=Math.max(...candidates);break}}
 const company=lines.find(line=>/\b(ltda\.?|s\.?a\.?s\.?|s\.?a\.?|limitada)\b/i.test(line)&&!/(consulting|generado por)/i.test(line));
 const merchant=company||lines.find(line=>/[A-Za-zÁÉÍÓÚÑáéíóúñ]{3}/.test(line)&&!/(nit|factura|fecha|tel|total|cajero|cliente|dirección|código)/i.test(line))||"Compra con comprobante";
 return{fecha,descripcion:merchant.slice(0,120),valor:valor?String(valor):"",observaciones:"Datos sugeridos mediante lectura automática. Verificar antes de guardar.",texto:normalizedText};
}

function matchRecurring(receipt:ReceiptDraft,items:GastoRecurrente[]){const text=normalized(`${receipt.descripcion} ${receipt.texto}`),amount=Number(receipt.valor);return items.find(item=>{const name=normalized(item.nombre),due=item.proxima_fecha_pago<=receipt.fecha,close=!amount||Math.abs(item.valor-amount)<=Math.max(item.valor*.15,1000);return item.activo&&due&&name.length>=4&&text.includes(name)&&close})||null}
function matchCategory(receipt:ReceiptDraft,items:Categoria[]){const text=normalized(`${receipt.descripcion} ${receipt.texto}`);const rules:[RegExp,string[]][]=[[/adidas|nike|puma|reebok|deportiv/,["Ropa deportiva","Calzado","Ropa"]],[/restaurante|burger|pizza|caf[eé]/,["Restaurantes","Cafeterías"]],[/gasolina|terpel|texaco|esso/,["Combustible"]],[/mercado|supermercado|exito|jumbo|d1|ara/,["Mercado"]]];for(const[pattern,names]of rules)if(pattern.test(text))for(const name of names){const found=items.find(item=>normalized(item.nombre)===normalized(name));if(found)return found.id}return items.find(item=>item.tipo.toLowerCase()==="gasto")?.id||null}

async function receiptFingerprint(receipt:ReceiptDraft){const stable=normalized(`${receipt.fecha}|${receipt.valor}|${receipt.descripcion}|${receipt.texto}`);const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(stable));return Array.from(new Uint8Array(bytes)).map(value=>value.toString(16).padStart(2,"0")).join("")}

export default function MovementsPage({accounts}:{accounts:Cuenta[]}){
 const[items,setItems]=useState<Movimiento[]>([]),[categories,setCategories]=useState<Categoria[]>([]),[recurrents,setRecurrents]=useState<GastoRecurrente[]>([]),[suggested,setSuggested]=useState<GastoRecurrente|null>(null),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Movimiento|null>(null),[deleting,setDeleting]=useState<Movimiento|null>(null),[receipt,setReceipt]=useState<ReceiptDraft|null>(null),[attachment,setAttachment]=useState<File|null>(null),[scanning,setScanning]=useState(false),[progress,setProgress]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{const[m,c,r]=await Promise.all([financeApi.movimientos(),financeApi.categorias(),financeApi.recurrentes()]);setItems(m);setCategories(c);setRecurrents(r)};useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.descripcion} ${x.categoria} ${x.cuenta}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const scan=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setScanning(true);setProgress(0);setError("");try{const{readReceipt}=await import("../receiptOcr");const draft=extractReceipt(await readReceipt(file,setProgress));draft.huella=await receiptFingerprint(draft);const categoryId=matchCategory(draft,categories);setReceipt(draft);setSuggested(matchRecurring(draft,recurrents));if(categoryId)setCategories(current=>[...current.filter(item=>item.id===categoryId),...current.filter(item=>item.id!==categoryId)]);setAttachment(file);setEditing(null);setOpen(true)}catch(err){setError(err instanceof Error?`No fue posible leer la factura: ${err.message}`:"No fue posible leer la factura") }finally{setScanning(false)}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget);const body={fecha:String(d.get("fecha")),descripcion:String(d.get("descripcion")),valor:Number(d.get("valor")),cuenta_id:Number(d.get("cuenta")),categoria_id:Number(d.get("categoria")),observaciones:String(d.get("observaciones")||""),huella:receipt?.huella};try{const recurringId=Number(d.get("recurrente")||0);const movement=recurringId&&!editing?await financeApi.pagarRecurrente(recurringId,{cuenta_id:body.cuenta_id,fecha_pago:body.fecha}):editing?await financeApi.actualizarMovimiento(editing.id,body):await financeApi.crearMovimiento(body);if(attachment&&!editing)await financeApi.adjuntarComprobante(movement.id,attachment);setOpen(false);setEditing(null);setReceipt(null);setAttachment(null);setSuggested(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible guardar") }finally{setSaving(false)}};
 const erase=async()=>{if(!deleting)return;setSaving(true);try{await financeApi.eliminarMovimiento(deleting.id);setDeleting(null);await load()}catch(err){setError(err instanceof Error?err.message:"No fue posible eliminar") }finally{setSaving(false)}};
 const startNew=()=>{const expense=categories.find(item=>item.tipo.toLowerCase()==="gasto");if(expense)setCategories(current=>[expense,...current.filter(item=>item.id!==expense.id)]);setEditing(null);setReceipt(null);setAttachment(null);setSuggested(null);setOpen(true)};
 return <section className="module-page"><div className="module-hero movements-hero"><div><span className="eyebrow text-violet-200">ACTIVIDAD FINANCIERA</span><h2>Movimientos sin ruido</h2><p>En web sube un PDF o imagen; en celular toma una foto de la factura.</p></div><div id="captura-comprobante" className="hero-actions"><label className={`scan-action camera-action ${scanning?"scanning":""}`}><input type="file" accept="image/*" capture="environment" onChange={scan} disabled={scanning}/>{scanning?<LoaderCircle className="animate-spin"/>:<Camera/>}{scanning?`Leyendo ${progress}%`:"Tomar foto"}</label><label className={`scan-action upload-action ${scanning?"scanning":""}`}><input type="file" accept="application/pdf,image/*" onChange={scan} disabled={scanning}/><FileUp/>{scanning?`${progress}%`:"Subir PDF o imagen"}</label><button className="primary-action" onClick={startNew}><Plus/> Nuevo movimiento</button></div><div className="module-orb"/></div>
 {error&&<p className="form-error">{error}</p>}<div className="movement-toolbar"><div className="movement-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por descripción, categoría o cuenta"/></div><span>{filtered.length} movimientos</span></div>
 <div className="movement-list">{filtered.map(item=>{const income=item.tipo.toLowerCase()==="ingreso";return <article key={item.id}><span className={income?"movement-icon income":"movement-icon expense"}>{income?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div className="movement-main"><strong>{item.descripcion||item.categoria}</strong><p>{item.categoria} · {item.cuenta}</p></div><time>{new Date(`${item.fecha}T00:00:00`).toLocaleDateString("es-CO",{day:"2-digit",month:"short"})}</time><strong className={income?"amount income":"amount expense"}>{income?"+":"−"}{new Intl.NumberFormat("es-CO",{style:"currency",currency:item.moneda}).format(Math.abs(item.valor))}</strong><div className="movement-actions"><button title="Editar" onClick={()=>{setEditing(item);setReceipt(null);setAttachment(null);setSuggested(null);setOpen(true)}}><Edit3/></button><button title="Eliminar" onClick={()=>setDeleting(item)}><Trash2/></button></div></article>})}{!filtered.length&&<div className="empty-state"><ReceiptText/><h3>No hay movimientos para mostrar</h3></div>}</div>
 {deleting&&<ConfirmDialog title="Eliminar movimiento" description={`FinanceOS revertirá automáticamente su efecto en el saldo de ${deleting.cuenta}.`} busy={saving} onCancel={()=>setDeleting(null)} onConfirm={()=>void erase()}/>} {open&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><form className="modern-modal receipt-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">{receipt?"FACTURA ANALIZADA":editing?"EDITAR MOVIMIENTO":"NUEVO MOVIMIENTO"}</span><h3>{receipt?"Confirma los datos extraídos":"Registra una operación"}</h3></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div>{attachment&&<div className="receipt-file"><Paperclip/><div><strong>{attachment.name}</strong><small>El comprobante se adjuntará al movimiento</small></div></div>}{suggested&&!editing&&<div className="recurring-suggestion"><span><ReceiptText/></span><div><strong>Parece un pago recurrente</strong><p>Coincide con “{suggested.nombre}” por {new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP"}).format(suggested.valor)}.</p></div><label>Registrar como<select name="recurrente" defaultValue={suggested.id}><option value={suggested.id}>Pago de {suggested.nombre}</option><option value="0">Movimiento normal</option></select></label></div>}<div className="form-grid"><label>Fecha<input name="fecha" type="date" defaultValue={receipt?.fecha||editing?.fecha||today()} required/></label><label>Valor<input name="valor" type="number" min=".01" step=".01" defaultValue={receipt?.valor||Math.abs(editing?.valor||0)||""} required/></label></div><label>Descripción<input name="descripcion" defaultValue={receipt?.descripcion||editing?.descripcion||""} required/></label><div className="form-grid"><label>Cuenta<select name="cuenta" defaultValue={editing?.cuenta_id}>{accounts.map(x=><option key={x.id} value={x.id}>{x.nombre} ({x.moneda})</option>)}</select></label><label>Categoría<select name="categoria" defaultValue={editing?.categoria_id}>{categories.map(x=><option key={x.id} value={x.id}>{x.tipo}: {x.nombre}</option>)}</select></label></div><label>Observaciones<input name="observaciones" defaultValue={receipt?.observaciones||editing?.observaciones||""}/></label><button className="modal-submit" disabled={saving}><ReceiptText/>{saving?"Guardando…":suggested?"Confirmar pago relacionado":"Guardar movimiento"}</button></form></div>}
 </section>;
}
