import { FormEvent, useEffect, useState } from "react";
import { Bell, CheckCircle2, CloudDownload, Database, HardDrive, Moon, Palette, Server, ShieldCheck, Sparkles, UserPlus, Users } from "lucide-react";
import { financeApi, RespaldoEstado, Usuario } from "../api";

export default function SettingsPage(){
  const[health,setHealth]=useState<{estado:string;version:string}|null>(null); const[backup,setBackup]=useState<RespaldoEstado|null>(null);
  const[users,setUsers]=useState<Usuario[]>([]); const[canManage,setCanManage]=useState(false); const[open,setOpen]=useState(false);
  const[downloading,setDownloading]=useState(false); const[message,setMessage]=useState(""); const[error,setError]=useState("");
  const loadUsers=async()=>{try{setUsers(await financeApi.usuarios());setCanManage(true)}catch{setCanManage(false)}};
  useEffect(()=>{Promise.all([financeApi.health(),financeApi.estadoRespaldo()]).then(([h,b])=>{setHealth(h);setBackup(b)});void loadUsers()},[]);
  const download=async()=>{setDownloading(true);setMessage("");try{const blob=await financeApi.descargarRespaldo();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`FinanceOS-respaldo-${new Date().toISOString().slice(0,10)}.zip`;link.click();URL.revokeObjectURL(url);setMessage("Respaldo creado correctamente")}catch(err){setMessage(err instanceof Error?err.message:"No fue posible descargar")}finally{setDownloading(false)}};
  const createUser=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");const data=new FormData(event.currentTarget);try{await financeApi.crearUsuario({nombre:String(data.get("nombre")),correo:String(data.get("correo")),password:String(data.get("password")),rol:String(data.get("rol")) as Usuario["rol"]});setOpen(false);await loadUsers()}catch(err){setError(err instanceof Error?err.message:"No fue posible crear el usuario")}};
  const toggleUser=async(user:Usuario)=>{setError("");try{await financeApi.actualizarUsuario(user.id,{activo:!user.activo,rol:user.rol});await loadUsers()}catch(err){setError(err instanceof Error?err.message:"No fue posible actualizar el usuario")}};
  return <section className="module-page">
    <div className="settings-title"><div><span className="eyebrow text-violet-200">SISTEMA · CONTROL</span><h2>Tu espacio, tus reglas</h2><p>Estado técnico, seguridad, usuarios y preferencias de FinanceOS.</p></div><span><ShieldCheck/></span></div>{error&&<div className="error-banner">{error}</div>}
    <div className="settings-layout"><div className="settings-column"><h3>Estado del sistema</h3>
      <article className="setting-card system-card"><span className="setting-icon green"><Server/></span><div><strong>API FinanceOS</strong><p>Servicio local · versión {health?.version??"…"}</p></div><span className="status-chip"><i/> {health?.estado==="ok"?"Operativa":"Comprobando"}</span></article>
      <article className="setting-card"><span className="setting-icon violet"><Database/></span><div><strong>Base de datos</strong><p>{backup?.motor?.toUpperCase()??"SQLite"} · {backup?`${(backup.tamano/1024).toFixed(1)} KB`:"Calculando…"}</p></div><CheckCircle2 className="setting-check"/></article><h3>Preferencias</h3>
      <article className="setting-card"><span className="setting-icon blue"><Moon/></span><div><strong>Apariencia espacial</strong><p>Tema oscuro optimizado para FinanceOS</p></div><button className="setting-toggle active"><i/></button></article>
      <article className="setting-card"><span className="setting-icon orange"><Bell/></span><div><strong>Alertas financieras</strong><p>Presupuestos, metas y pagos próximos</p></div><button className="setting-toggle active"><i/></button></article></div>
      <div className="settings-column"><h3>Seguridad y datos</h3><article className="backup-card"><div className="backup-visual"><HardDrive/><span className="backup-pulse"/></div><span className="eyebrow">RESPALDO LOCAL</span><h3>Protege tu historia financiera</h3><p>Genera un ZIP con la base de datos y comprobantes. Tus datos permanecen en tu dispositivo.</p><div className="backup-meta"><span>Última modificación</span><strong>{backup?.modificado?new Date(backup.modificado).toLocaleString("es-CO"):"Sin información"}</strong></div><button onClick={()=>void download()} disabled={downloading}><CloudDownload/>{downloading?"Preparando…":"Descargar respaldo"}</button>{message&&<small>{message}</small>}</article>
      <article className="setting-card intelligence"><span className="setting-icon violet"><Sparkles/></span><div><strong>FinanceOS Intelligence</strong><p>Preparado para recomendaciones con IA en una próxima etapa.</p></div></article><article className="setting-card"><span className="setting-icon blue"><Palette/></span><div><strong>Sistema visual</strong><p>React + Tailwind · experiencia responsive</p></div><CheckCircle2 className="setting-check"/></article></div></div>
    {canManage&&<section className="users-panel"><div className="panel-heading"><div><span className="eyebrow">ACCESO PRIVADO</span><h3>Personas con acceso</h3><p>Cada usuario tiene un espacio financiero aislado; no puede consultar datos ajenos.</p></div><button className="primary-action" onClick={()=>setOpen(true)}><UserPlus/> Nuevo usuario</button></div><div className="users-grid">{users.map(user=><article key={user.id}><span className="user-avatar"><Users/></span><div><strong>{user.nombre}</strong><p>{user.correo}</p></div><span className={`role-chip ${user.rol}`}>{user.rol}</span><button className={`user-state ${user.activo?"active":""}`} onClick={()=>void toggleUser(user)}>{user.activo?"Activo":"Inactivo"}</button></article>)}</div></section>}
    {open&&<div className="modal-backdrop"><form className="account-modal user-modal" onSubmit={createUser}><div className="modal-head"><div><span className="eyebrow">ACCESO SEGURO</span><h3>Crear usuario</h3></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Nombre<input name="nombre" minLength={2} maxLength={100} required/></label><label>Correo<input name="correo" type="email" required/></label><label>Contraseña temporal<input name="password" type="password" minLength={12} required/><small>Mínimo 12 caracteres. La persona iniciará sesión con esta clave.</small></label><label>Rol<select name="rol" defaultValue="usuario"><option value="usuario">Usuario</option><option value="administrador">Administrador</option></select></label><button className="modal-submit" type="submit"><UserPlus/> Crear acceso privado</button></form></div>}
  </section>
}
