import { useEffect, useState } from "react";
import { Bell, CheckCircle2, CloudDownload, Database, HardDrive, Moon, Palette, Server, ShieldCheck, Sparkles } from "lucide-react";
import { financeApi, RespaldoEstado } from "../api";

export default function SettingsPage(){const[health,setHealth]=useState<{estado:string;version:string}|null>(null);const[backup,setBackup]=useState<RespaldoEstado|null>(null);const[downloading,setDownloading]=useState(false);const[message,setMessage]=useState("");useEffect(()=>{Promise.all([financeApi.health(),financeApi.estadoRespaldo()]).then(([h,b])=>{setHealth(h);setBackup(b)})},[]);
const download=async()=>{setDownloading(true);setMessage("");try{const blob=await financeApi.descargarRespaldo();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`FinanceOS-respaldo-${new Date().toISOString().slice(0,10)}.zip`;link.click();URL.revokeObjectURL(url);setMessage("Respaldo creado correctamente") }catch(err){setMessage(err instanceof Error?err.message:"No fue posible descargar") }finally{setDownloading(false)}};
return <section className="module-page"><div className="settings-title"><div><span className="eyebrow text-violet-200">SISTEMA · CONTROL</span><h2>Tu espacio, tus reglas</h2><p>Estado técnico, seguridad y preferencias de FinanceOS.</p></div><span><ShieldCheck/></span></div>
<div className="settings-layout"><div className="settings-column"><h3>Estado del sistema</h3><article className="setting-card system-card"><span className="setting-icon green"><Server/></span><div><strong>API FinanceOS</strong><p>Servicio local · versión {health?.version??"…"}</p></div><span className="status-chip"><i/> {health?.estado==="ok"?"Operativa":"Comprobando"}</span></article><article className="setting-card"><span className="setting-icon violet"><Database/></span><div><strong>Base de datos</strong><p>{backup?.motor?.toUpperCase()??"SQLite"} · {backup?`${(backup.tamano/1024).toFixed(1)} KB`:"Calculando…"}</p></div><CheckCircle2 className="setting-check"/></article><h3>Preferencias</h3><article className="setting-card"><span className="setting-icon blue"><Moon/></span><div><strong>Apariencia espacial</strong><p>Tema oscuro optimizado para FinanceOS</p></div><button className="setting-toggle active"><i/></button></article><article className="setting-card"><span className="setting-icon orange"><Bell/></span><div><strong>Alertas financieras</strong><p>Presupuestos, metas y pagos próximos</p></div><button className="setting-toggle active"><i/></button></article></div>
<div className="settings-column"><h3>Seguridad y datos</h3><article className="backup-card"><div className="backup-visual"><HardDrive/><span className="backup-pulse"/></div><span className="eyebrow">RESPALDO LOCAL</span><h3>Protege tu historia financiera</h3><p>Genera un archivo ZIP con la base de datos y los comprobantes almacenados. Tus datos permanecen en tu dispositivo.</p><div className="backup-meta"><span>Última modificación</span><strong>{backup?.modificado?new Date(backup.modificado).toLocaleString("es-CO"):"Sin información"}</strong></div><button onClick={()=>void download()} disabled={downloading}><CloudDownload/>{downloading?"Preparando…":"Descargar respaldo"}</button>{message&&<small>{message}</small>}</article><article className="setting-card intelligence"><span className="setting-icon violet"><Sparkles/></span><div><strong>FinanceOS Intelligence</strong><p>Preparado para recomendaciones con IA en una próxima etapa.</p></div></article><article className="setting-card"><span className="setting-icon blue"><Palette/></span><div><strong>Sistema visual</strong><p>React + Tailwind · experiencia responsive</p></div><CheckCircle2 className="setting-check"/></article></div></div></section>}
