import { FormEvent, useEffect, useState } from "react";
import { ArrowDown, ArrowLeftRight, Landmark, Plus, Trash2, X } from "lucide-react";
import { Cuenta, financeApi, Transferencia } from "../api";
import ConfirmDialog from "../components/ConfirmDialog";

export default function TransfersPage({ accounts, onChanged }: { accounts: Cuenta[]; onChanged: () => Promise<void> }) {
  const [items, setItems] = useState<Transferencia[]>([]), [open, setOpen] = useState(false);
  const [deleting, setDeleting] = useState<Transferencia | null>(null), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const load = async () => setItems(await financeApi.transferencias());
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); const data = new FormData(event.currentTarget); try { await financeApi.crearTransferencia({ fecha: String(data.get("fecha")), cuenta_origen_id: Number(data.get("origen")), cuenta_destino_id: Number(data.get("destino")), valor: Number(data.get("valor")), descripcion: String(data.get("descripcion") || "") }); setOpen(false); await Promise.all([load(), onChanged()]); } catch (err) { setError(err instanceof Error ? err.message : "No fue posible transferir"); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; setSaving(true); try { await financeApi.eliminarTransferencia(deleting.id); setDeleting(null); await Promise.all([load(), onChanged()]); } catch (err) { setError(err instanceof Error ? err.message : "No fue posible eliminar"); } finally { setSaving(false); } };
  return <section className="module-page"><div className="module-hero transfer-hero"><div><span className="eyebrow text-cyan-200">MOVIMIENTO INTERNO</span><h2>Dinero en tránsito</h2><p>Mueve saldo entre tus cuentas sin alterar ingresos ni gastos.</p></div><button className="primary-action" onClick={() => setOpen(true)}><Plus /> Nueva transferencia</button><div className="module-orb" /></div>{error && <p className="form-error">{error}</p>}<div className="transfer-flow">{items.map(item => <article key={item.id}><div className="transfer-date">{new Date(`${item.fecha}T00:00:00`).toLocaleDateString("es-CO", { day: "2-digit", month: "short" })}</div><div className="transfer-account"><span><Landmark /></span><div><small>ORIGEN</small><strong>{item.cuenta_origen}</strong></div></div><div className="transfer-arrow"><ArrowDown /></div><div className="transfer-account destination"><span><Landmark /></span><div><small>DESTINO</small><strong>{item.cuenta_destino}</strong></div></div><div className="transfer-amount"><strong>{new Intl.NumberFormat("es-CO", { style: "currency", currency: item.moneda }).format(item.valor)}</strong><span>{item.descripcion || "Transferencia"}</span></div><button className="inline-delete" aria-label="Eliminar transferencia" onClick={() => setDeleting(item)}><Trash2 /></button></article>)}{!items.length && <div className="empty-state transfer-empty"><ArrowLeftRight /><h3>Aún no has movido dinero</h3><p>Las transferencias aparecerán aquí.</p></div>}</div>
    {open && <div className="modal-layer"><button className="modal-backdrop" aria-label="Cerrar" onClick={() => setOpen(false)} /><form className="modern-modal" onSubmit={submit}><div className="flex items-start justify-between"><div><span className="eyebrow">NUEVA TRANSFERENCIA</span><h3>Mueve tu saldo</h3></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X /></button></div><label>Fecha<input name="fecha" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><div className="form-grid"><label>Cuenta de origen<select name="origen">{accounts.map(x => <option value={x.id} key={x.id}>{x.nombre} ({x.moneda})</option>)}</select></label><label>Cuenta de destino<select name="destino">{accounts.map(x => <option value={x.id} key={x.id}>{x.nombre} ({x.moneda})</option>)}</select></label></div><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required /></label><label>Descripción<input name="descripcion" placeholder="Ej: Ahorro mensual" /></label><button className="modal-submit" disabled={saving}><ArrowLeftRight />{saving ? "Transfiriendo…" : "Realizar transferencia"}</button></form></div>}{deleting && <ConfirmDialog title="Eliminar transferencia" description="Se revertirán los saldos de origen y destino para mantener el patrimonio consistente." busy={saving} onCancel={() => setDeleting(null)} onConfirm={remove} />}</section>;
}
